require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/air_connections", type: :request do
  # AirConnection. As you add validations to AirConnection, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      AirConnection.create! valid_attributes
      get air_connections_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      air_connection = AirConnection.create! valid_attributes
      get air_connection_url(air_connection)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_air_connection_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      air_connection = AirConnection.create! valid_attributes
      get edit_air_connection_url(air_connection)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AirConnection" do
        expect {
          post air_connections_url, params: {air_connection: valid_attributes}
        }.to change(AirConnection, :count).by(1)
      end

      it "redirects to the created air_connection" do
        post air_connections_url, params: {air_connection: valid_attributes}
        expect(response).to redirect_to(air_connection_url(AirConnection.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AirConnection" do
        expect {
          post air_connections_url, params: {air_connection: invalid_attributes}
        }.to change(AirConnection, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post air_connections_url, params: {air_connection: invalid_attributes}
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested air_connection" do
        air_connection = AirConnection.create! valid_attributes
        patch air_connection_url(air_connection), params: {air_connection: new_attributes}
        air_connection.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the air_connection" do
        air_connection = AirConnection.create! valid_attributes
        patch air_connection_url(air_connection), params: {air_connection: new_attributes}
        air_connection.reload
        expect(response).to redirect_to(air_connection_url(air_connection))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        air_connection = AirConnection.create! valid_attributes
        patch air_connection_url(air_connection), params: {air_connection: invalid_attributes}
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested air_connection" do
      air_connection = AirConnection.create! valid_attributes
      expect {
        delete air_connection_url(air_connection)
      }.to change(AirConnection, :count).by(-1)
    end

    it "redirects to the air_connections list" do
      air_connection = AirConnection.create! valid_attributes
      delete air_connection_url(air_connection)
      expect(response).to redirect_to(air_connections_url)
    end
  end
end
